language: node_js
node_js: "12"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux
  - osx


cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y bsdtar; fi # needed for pacman
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y rpm; fi # needed for rpm
  #- npm install -g npm@latest


install:
  - npm install


before_script:
  #- npm audit --json >> $TRAVIS_BUILD_DIR/audit/report.json || true
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi


services:
  - xvfb

script:
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
  - node --version
  - npm --version
  - npm test
  - npm audit
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run build-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run build-mac; fi

after_success:


after_failure:


before_deploy:


deploy:


after_deploy:
