image: Visual Studio 2017

platform:
  - x64

os:
  - unstable

environment:
  GH_TOKEN:
    secure: zdmqj3G0vY5FgdqkER3/v/Cgv9m8XORyyH7xnRRtc9+SAX2mj0XnmjewLh7U2rL2

cache:
  - node_modules
  - '%USERPROFILE%\.electron'


install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run build-win

test: off
