image: Visual Studio 2017

platform:
  - x64

os:
  - unstable

environment:
  GH_TOKEN:
    secure: cd77f170b91f768a4824cc3dedb37d4be89b7e3f

cache:
  - node_modules
  - '%USERPROFILE%\.electron'


install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run build-win

test: off
