image: Visual Studio 2017

platform:
  - x64

os:
  - unstable

environment:
  GH_TOKEN:
    secure: 6c63f112c3db0f970e20b17ba939c975536f262f

cache:
  - node_modules
  - '%USERPROFILE%\.electron'


install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run build-win

test: off
